production:
  primary: &primary_production
    adapter: sqlite3
    database: /data/production.sqlite3
  cable:
    <<: *primary_production
    database: /data/production_cable.sqlite3
    migrations_paths: db/cable_migrate